{
 "title": "Cluster Linking",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_log_log_size, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kafka_server_replicamanager_blockedonmirrorsourcepartitioncount{namespace=\"${namespace}\"}, pod)"
    }
   },
   {
    "name": "link",
    "label": "link",
    "query": {
     "query": "label_values(kafka_server_cluster_link_fetcher_metrics_connection_count,link_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Link status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_link_count{link_name=~\"$link\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{link_name}} - state {{state}}"
    }
   ]
  },
  {
   "title": "Mirror topic status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_mirror_topic_count{link_name=~\"$link\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{link_name}} - state {{state}}"
    }
   ]
  },
  {
   "title": "Mirror Partition Count",
   "type": "gauge",
   "description": "Number of actively mirrored partitions for which the broker is leader",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_metrics_mirror_partition_count{link_name=~\"$link\",namespace=~\"$namespace\"})",
     "legendFormat": "{{link_name}}"
    }
   ]
  },
  {
   "title": "Mirrored Topic under replicated.",
   "type": "gauge",
   "description": "Number of mirrored partitions that are under replicated.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedmirrorpartitions{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Mirrored Topic under min isr.",
   "type": "gauge",
   "description": "Number of mirrored partitions that are under min ISR.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underminisrmirrorpartitioncount{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Mirrored Partitions Blocked",
   "type": "gauge",
   "description": "Number of mirrored partitions that are blocked on fetching data due to issues on the source cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_blockedonmirrorsourcepartitioncount{namespace=~\"$namespace\"})",
     "legendFormat": " {{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Link Fetcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Lag",
   "type": "timeseries",
   "description": "Maximum lag in messages between the replicas on the destination cluster and the leader replica on the source cluster. Provides an indication of overall cluster link health and a relative measure of whether the destination cluster is lagging behind.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_server_link_clusterlinkfetchermanager_maxlag{link_name=~\"$link\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{link_name}}"
    }
   ]
  },
  {
   "title": "Dead Thread Count",
   "type": "timeseries",
   "description": "Number of dead threads of type ClusterLinkThread, where a dead thread is indicative of an issue with fetching from the source cluster for a partition.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kafka_server_link_clusterlinkfetchermanager_deadthreadcount{link_name=~\"$link\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{link_name}}"
    }
   ]
  },
  {
   "title": "Total Fetch Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kafka_server_link_clusterlinkfetchermanager_totalfetchrate{link_name=~\"$link\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{link_name}}"
    }
   ]
  },
  {
   "title": "Failed Partitions Count",
   "type": "timeseries",
   "description": "Number of failed mirror partitions for which the broker is leader. A partition may be in a failed state if the source partition’s epoch has gone backwards; for example, if the topic was recreated.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "kafka_server_link_clusterlinkfetchermanager_failedpartitionscount{link_name=~\"$link\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{link_name}}"
    }
   ]
  },
  {
   "title": "Replica Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throttled Link Replica Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_throttledclusterlinkreplicaspersec{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Metrics ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Time Ms",
   "type": "timeseries",
   "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems{request=\"CreateClusterLinks\"}[5m]))",
     "legendFormat": "CreateClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems{request=\"DeleteClusterLinks\"}[5m]))",
     "legendFormat": "DeleteClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems{request=\"ListClusterLinks\"}[5m]))",
     "legendFormat": "ListClusterLinks"
    }
   ]
  },
  {
   "title": "Local Time Ms",
   "type": "timeseries",
   "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_localtimems{request=\"CreateClusterLinks\"}[5m]))",
     "legendFormat": "CreateClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_localtimems{request=\"DeleteClusterLinks\"}[5m]))",
     "legendFormat": "DeleteClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_localtimems{request=\"ListClusterLinks\"}[5m]))",
     "legendFormat": "ListClusterLinks"
    }
   ]
  },
  {
   "title": "Request Queue Time Ms",
   "type": "timeseries",
   "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestqueuetimems{request=\"CreateClusterLinks\"}[5m]))",
     "legendFormat": "CreateClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestqueuetimems{request=\"DeleteClusterLinks\"}[5m]))",
     "legendFormat": "DeleteClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestqueuetimems{request=\"ListClusterLinks\"}[5m]))",
     "legendFormat": "ListClusterLinks"
    }
   ]
  },
  {
   "title": "Response Queue Time Ms",
   "type": "timeseries",
   "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsequeuetimems{request=\"CreateClusterLinks\"}[5m]))",
     "legendFormat": "CreateClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsequeuetimems{request=\"DeleteClusterLinks\"}[5m]))",
     "legendFormat": "DeleteClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsequeuetimems{request=\"ListClusterLinks\"}[5m]))",
     "legendFormat": "ListClusterLinks"
    }
   ]
  },
  {
   "title": "Remote Time Ms",
   "type": "timeseries",
   "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_remotetimems{request=\"CreateClusterLinks\"}[5m]))",
     "legendFormat": "CreateClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_remotetimems{request=\"DeleteClusterLinks\"}[5m]))",
     "legendFormat": "DeleteClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_remotetimems{request=\"ListClusterLinks\"}[5m]))",
     "legendFormat": "ListClusterLinks"
    }
   ]
  },
  {
   "title": "Response Send Time Ms",
   "type": "timeseries",
   "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsesendtimems{request=\"CreateClusterLinks\"}[5m]))",
     "legendFormat": "CreateClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsesendtimems{request=\"DeleteClusterLinks\"}[5m]))",
     "legendFormat": "DeleteClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsesendtimems{request=\"ListClusterLinks\"}[5m]))",
     "legendFormat": "ListClusterLinks"
    }
   ]
  },
  {
   "title": "Throttle Time Ms",
   "type": "timeseries",
   "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_throttletimems{request=\"CreateClusterLinks\"}[5m]))",
     "legendFormat": "CreateClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_throttletimems{request=\"DeleteClusterLinks\"}[5m]))",
     "legendFormat": "DeleteClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_throttletimems{request=\"ListClusterLinks\"}[5m]))",
     "legendFormat": "ListClusterLinks"
    }
   ]
  },
  {
   "title": "Response Send IO Time Ms",
   "type": "timeseries",
   "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsesendiotimems{request=\"CreateClusterLinks\"}[5m]))",
     "legendFormat": "CreateClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsesendiotimems{request=\"DeleteClusterLinks\"}[5m]))",
     "legendFormat": "DeleteClusterLinks"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsesendiotimems{request=\"ListClusterLinks\"}[5m]))",
     "legendFormat": "ListClusterLinks"
    }
   ]
  }
 ]
}