{
 "title": "Kafka Quotas",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate, namespace)"
    }
   },
   {
    "name": "broker_id",
    "label": "Pod",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate, pod)"
    }
   },
   { "name": "user", "label": "User", "query": { "query": "label_values(user)" } },
   { "name": "client_id", "label": "Client Id", "query": { "query": "label_values(client_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Produce Byte Rate",
   "type": "timeseries",
   "description": "Indicates the data produce rate of the client in bytes/sec",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, kafka_server_produce_byte_rate{user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker_id\",namespace=\"$namespace\",app=\"kafka\"})",
     "legendFormat": "User: {{ user }} - Client: {{ client_id }} @ Broker: {{ pod }}"
    }
   ]
  },
  {
   "title": "Fetch Byte Rate",
   "type": "timeseries",
   "description": "Indicates the data consume rate of the client in bytes/sec",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, kafka_server_fetch_byte_rate{user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker_id\",namespace=\"$namespace\",app=\"kafka\"})",
     "legendFormat": "User: {{ user }} - Client: {{ client_id }} @ Broker: {{ pod }}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "timeseries",
   "description": "Indicates the percentage of time spent in broker network and I/O threads to process requests from client group",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, kafka_server_request_request_time{user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker_id\",namespace=\"$namespace\",app=\"kafka\"})",
     "legendFormat": "User: {{ user }} - Client: {{ client_id }} @ Broker: {{ pod }}"
    }
   ]
  },
  {
   "title": "Produce Bandwidth Throttle",
   "type": "timeseries",
   "description": "Indicates the amount of time in ms the client was throttled",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_produce_throttle_time{user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker_id\",namespace=\"$namespace\",app=\"kafka\"} > 0",
     "legendFormat": "User: {{ user }} - Client: {{ client_id }} @ Broker: {{ pod }}"
    }
   ]
  },
  {
   "title": "Fetch Bandwidth Throttle",
   "type": "timeseries",
   "description": "Indicates the amount of time in ms the client was throttled",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_fetch_throttle_time{user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker_id\",namespace=\"$namespace\",app=\"kafka\"} > 0",
     "legendFormat": "User: {{ user }} - Client: {{ client_id }} @ Broker: {{ pod }}"
    }
   ]
  },
  {
   "title": "Request Throttle",
   "type": "timeseries",
   "description": "Indicates the amount of time in ms the client was throttled",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_request_throttle_time{user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker_id\",namespace=\"$namespace\",app=\"kafka\"} > 0",
     "legendFormat": "User: {{ user }} - Client: {{ client_id }} @ Broker: {{ pod }}"
    }
   ]
  }
 ]
}