apiVersion: v1
data:
  plain-users.json: ewogICAgImRmZWRlcmljbyI6ICJwYXNzd29yZCIsCiAgICAiZGFuZWxsYSI6ICJwYXNzd29yZCIsCiAgICAic29tZXVzZXIiOiAicGFzc3dvcmQiLAogICAgImNvbm5lY3QiOiAicGFzc3dvcmQiCn0=
kind: Secret
metadata:
  creationTimestamp: null
  name: kafka-users
