---
# Kafka Topic
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: app.internal.perf.topic
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 2
  configs:
    cleanup.policy: "delete"


---
# Client Connection Properties - base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: kafka-app-noauth-properties
  namespace: confluent
type: Opaque
data:
  client.properties: Ym9vdHN0cmFwLnNlcnZlcnM9a2Fma2EuY29uZmx1ZW50LnN2Yy5jbHVzdGVyLmxvY2FsOjkwNzEKc2VjdXJpdHkucHJvdG9jb2w9UExBSU5URVhUCmFja3M9YWxs


---
# Kafka Perf Producer as Pod
apiVersion: v1
kind: Pod
metadata:
  name: perf-producer-app
  namespace: confluent
  labels:
    component: producer-app
spec:
  containers:
  - image: confluentinc/cp-kafka:7.8.0 
    name: perf-producer-app
    command:
    - /bin/sh
    - -c
    - |
      kafka-producer-perf-test \
        --topic app.internal.perf.topic  \
        --record-size 64 \
        --throughput 10 \
        --producer-props bootstrap.servers=kafka.confluent.svc.cluster.local:9071 \
        --producer.config /mnt/client.properties \
        --num-records 1000
    volumeMounts:
      - name: client-properties
        mountPath: /mnt
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: client-properties
      secret:
        secretName: kafka-app-noauth-properties


---
# Kafka Perf Consumer as Pod
apiVersion: v1
kind: Pod
metadata:
  name: perf-consumer-app
  namespace: confluent  
  labels:
    component: perf-consumer-app  
spec:
  containers:
  - image: confluentinc/cp-kafka:7.8.0 
    name: perf-consumer-app
    command:
    - /bin/sh
    - -c
    - |
      kafka-console-consumer \
        --bootstrap-server kafka.confluent.svc.cluster.local:9071 \
        --consumer.config /mnt/client.properties \
        --property print.partition=true \
        --property print.offset=true \
        --topic app.internal.perf.topic \
        --from-beginning \
        --timeout-ms 30000
    volumeMounts:
        - name: client-properties
          mountPath: /mnt
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: client-properties
      secret:
        secretName: kafka-app-noauth-properties
