apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: pizza-orders-datagen-connector
  namespace: confluent
spec:
  name: pizza-orders-datagen
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  configs:
    quickstart: "pizza_orders"
    kafka.topic: "pizza-orders"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"    
    max.interval: "5000"
    iterations: "10000"
  restartPolicy:
    type: OnFailure
    maxRetry: 5