apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: person.data
  namespace: confluent
spec:
  # kafkaRestClassRef:
  #   name: krc-cfk
  replicas: 3
  partitionCount: 2
  configs:
    cleanup.policy: "delete"