---
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    hostname: keycloak
    container_name: keycloak
    #command: ["start-dev", "--log-level=DEBUG", "--health-enabled=true", "--import-realm"]
    command: ["start-dev", "--health-enabled=true", "--import-realm"]
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live' ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./realms/demo-realm.json:/opt/keycloak/data/import/realm.json
      # - ./realms/simple-realm.json:/opt/keycloak/data/import/realm.json