---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfk-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:DennisFederico/cflt.cfk.demo.git
    targetRevision: HEAD
    path: gitops/repo/cfk
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: confluent
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
  sources: []