apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: metatopic
  namespace: confluent
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    application.owner: "dfederico"
spec:
  kafkaRestClassRef:
    name: default
    namespace: confluent
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
    min.insync.replicas: "2"    