apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: pizza-orders
  namespace: confluent
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  kafkaRestClassRef:
    name: default
    namespace: confluent
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"
    min.insync.replicas: "2"
