apiVersion: v1
data:
  basic.txt: ZGZlZGVyaWNvOnBhc3N3b3JkLCBhZG1pbgpjb250cm9sY2VudGVyOnBhc3N3b3JkLCBhZG1pbg==
kind: Secret
metadata:
  creationTimestamp: null
  name: ksqldb-basic
  namespace: confluent
