---
services:
  mysql:
    # *---------------------------------------------------------------------------------------*
    # To connect to the DB:     
    # docker exec -it mysql bash -c 'mysql -u root -pdebezium'
    # GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'mysqluser';
    # *---------------------------------------------------------------------------------------*
    image: quay.io/debezium/example-mysql:latest 
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
    # volumes:
    #  - ./config:/docker-entrypoint-initdb.d/