---
services:
  mysql:
    # *---------------------------------------------------------------------------------------*
    # To connect to the DB:     
    # docker exec -it mysql bash -c 'mysql -u root -pdebezium'
    # Note that the user for CDC is debezium/debezium
    # *---------------------------------------------------------------------------------------*
    image: quay.io/debezium/example-mysql:latest 
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpass
    volumes:
     - ./config:/docker-entrypoint-initdb.d/